2023-08-14 03:10:53,729 INFO    MainThread:289868 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_setup.py:_flush():76] Configure stats pid to 289868
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntu/.config/wandb/settings
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntu/dolphin_classification/notebooks/wandb/settings
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_init.py:_log_setup():507] Logging user logs to /home/ubuntu/dolphin_classification/notebooks/wandb/run-20230814_031053-26yven7h/logs/debug.log
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_init.py:_log_setup():508] Logging internal logs to /home/ubuntu/dolphin_classification/notebooks/wandb/run-20230814_031053-26yven7h/logs/debug-internal.log
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_init.py:init():547] calling init triggers
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'arch': 'InceptionV4'}
2023-08-14 03:10:53,730 INFO    MainThread:289868 [wandb_init.py:init():571] re-initializing run, found existing run on stack: by4gyeij
2023-08-14 03:10:53,732 INFO    MainThread:289868 [wandb_run.py:_finish():1894] finishing run yashchks87/dolphin/by4gyeij
2023-08-14 03:10:53,732 INFO    MainThread:289868 [jupyter.py:save_history():445] not saving jupyter history
2023-08-14 03:10:53,732 INFO    MainThread:289868 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-08-14 03:10:53,732 INFO    MainThread:289868 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-08-14 03:10:53,732 INFO    MainThread:289868 [wandb_run.py:_atexit_cleanup():2128] got exitcode: 0
2023-08-14 03:10:53,732 INFO    MainThread:289868 [wandb_run.py:_restore():2111] restore
2023-08-14 03:10:53,732 INFO    MainThread:289868 [wandb_run.py:_restore():2117] restore done
